// <auto-generated />
namespace O2O.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _202012241707 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_202012241707));
        
        string IMigrationMetadata.Id
        {
            get { return "202012240907305_202012241707"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
