// <auto-generated />
namespace O2O.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _202009101657 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_202009101657));
        
        string IMigrationMetadata.Id
        {
            get { return "202009100859300_202009101657"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
