// <auto-generated />
namespace O2O.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _06171116 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_06171116));
        
        string IMigrationMetadata.Id
        {
            get { return "202006170316201_06171116"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
