// <auto-generated />
namespace O2O.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class 新增预订商品表 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(新增预订商品表));
        
        string IMigrationMetadata.Id
        {
            get { return "202007200228151_新增预订商品表"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
